
# different language chart settings
en = [{'dashboard_title':'Customer Connected to WSP',
        'field_to_check':'does_customer_have_a_connection',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'customer_connected_to_wsp',
        'chart_type':'pie'
    },
    {'dashboard_title':'Account Details Known',
        'field_to_check':'customer_have_a_connection',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[{'field_name':'does_customer_have_a_connection',
           'required_value':'Yes'
        }],
        'chart_id':'account_details_known',
        'chart_type':'doughnut'
    },
    {'dashboard_title':'Customer Willing to be Connected',
        'field_to_check':'customer_willing_to_be_connected',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[{'field_name':'does_customer_have_a_connection',
           'required_value':'No'
        }],
        'chart_id':'customer_willing_to_be_connected',
        'chart_type':'bar'
    },
    # {'dashboard_title':'Potential Customers Connectable',
    #     'field_to_check':,
        # 'data_fomart':'single_dataset',
    #     'other_fields_to_check':[{'field_name': ,
    #        'required_value':
    #     }]
    # },
    # {'dashboard_title':'Reasons Customer is not Connected to WSP',
    #     'field_to_check':'customer_willing_to_be_connected',
    # 'data_fomart':'single_dataset',
    #     'other_fields_to_check':[{'field_name':,
    #        'required_value':
    #     }]
    # },
    {'dashboard_title':'Connection Status',
        'custom_function':False,
        'field_to_check':'connection_status',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'connection_status',
        'chart_type':'polarArea'
    },
    {'dashboard_title':'Disconnection Duration',
        'custom_function':False,
        'field_to_check':'disconnection_duration',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[{'field_name':'does_customer_have_a_connection',
           'required_value':'yes'
        }],
        'chart_id':'disconnection_duration',
        'chart_type':'doughnut'
    },
    {'dashboard_title':'Alternative Sources of Water',
        'custom_function':False,
        'field_to_check':'water_sources',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'alternative_sources_of_water',
        'chart_type':'horizontalBar'
    },
    {'dashboard_title':'Connection Status vs Account Known',
        'custom_function':False,
        'field_to_check':'connection_status',
        'data_fomart':'multiple_dataset',
        'secondary_field':'customer_have_a_connection',
        'other_fields_to_check':[{'field_name':'does_customer_have_a_connection',
           'required_value':'yes'
        }],
        'chart_id':'connection_status_vs_account_known',
        'chart_type':'bar'
    },
    {'dashboard_title':'Billing Status',
        'custom_function':False,
        'field_to_check':'billing_status',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[{'field_name':'does_customer_have_a_connection',
           'required_value':'yes'
        }],
        'chart_id':'billing_status',
        'chart_type':'bar'
    },
    {'dashboard_title':'Billing Status vs Connection Status',
        'custom_function':False,
        'field_to_check':'billing_status',
        'data_fomart':'multiple_dataset',
        'secondary_field':'connection_status',
        'other_fields_to_check':[],
        'chart_id':'billing_status_vs_connection_status',
        'chart_type':'bar'
    },
    {'dashboard_title':'Frequency of Bill Delivery',
        'custom_function':False,
        'field_to_check':'frequency_of_bill_delivery',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'frequency_of_bill_delivery',
        'chart_type':'bar'
    },
    {'dashboard_title':'Frequency of Bill Delivery VS Account Status',
        'custom_function':False,
        'field_to_check':'frequency_of_bill_delivery',
        'secondary_field':'connection_status',
        'data_fomart':'multiple_dataset',
        'other_fields_to_check':[],
        'chart_id':'frequency_of_bill_delivery_vs_connection_status',
        'chart_type':'bar'
    },
    {'dashboard_title':'How Often Do You Recieve Water',
        'custom_function':False,
        'field_to_check':'how_often_do_you_receive_water',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'how_often_do_you_receive_water',
        'chart_type':'polarArea'
    },
    {'dashboard_title':'Reasons not Billed',
        'custom_function':False,
        'field_to_check':'why_customer_is_not_billed',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[{'field_name':'does_customer_have_a_connection',
           'required_value':'yes'},{'field_name':'billing_status',
           'required_value':'not_billed'}
        ],
        'chart_id':'reasons_not_billed',
        'chart_type':'pie'
    },
    {'dashboard_title':'Daily Hours of Supply',
        'custom_function':False,
        'field_to_check':'daily_hours',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'daily_hours',
        'chart_type':'doughnut'
    },
    {'dashboard_title':'Clients who Recieve Water During the Week',
        'custom_function':False,
        'field_to_check':'daily_hours',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'daily_hours',
        'chart_type':'pie'
    },
    {'dashboard_title':'Last Time to Recieve Water',
        'custom_function':False,
        'field_to_check':'last_time_to_receive_water',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'last_time_to_receive_water',
        'chart_type':'bar'
    },
    {'dashboard_title':'Water Meter Connected',
        'custom_function':False,
        'field_to_check':'water_connection',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'water_connection',
        'chart_type':'bar'
    },
    {'dashboard_title':'Meter Status',
        'custom_function':False,
        'field_to_check':'meter_status',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'meter_status',
        'chart_type':'pie'
    },
    {'dashboard_title':'Meter Status Vs Connection Status',
        'custom_function':False,
        'field_to_check':'meter_status',
        'secondary_field':'connection_status',
        'data_fomart':'multiple_dataset',
        'other_fields_to_check':[],
        'chart_id':'meter_status_vs_connection_status',
        'chart_type':'bar'
    },
    {'dashboard_title':'Meter Material',
        'custom_function':False,
        'field_to_check':'meter_material',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'meter_material',
        'chart_type':'doughnut'
    },
    {'dashboard_title':'Meter Location',
        'custom_function':False,
        'field_to_check':'meter_location',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'meter_location',
        'chart_type':'bar'
    },
    {'dashboard_title':'Meter Settlement',
        'custom_function':False,
        'field_to_check':'meter_settlement',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'meter_settlement',
        'chart_type':'pie'
    },
    {'dashboard_title':'Meter Flow Direction',
        'custom_function':False,
        'field_to_check':'meter_flow_direction',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'meter_flow_direction',
        'chart_type':'polarArea'
    },
    {'dashboard_title':'Meter Read Monthly',
        'custom_function':False,
        'field_to_check':'meter_read_monthly',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'meter_read_monthly',
        'chart_type':'doughnut'
    },
    {'dashboard_title':'Meter Class',
        'custom_function':False,
        'field_to_check':'meter_class',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'meter_class',
        'chart_type':'bar'
    },
    {'dashboard_title':'Meter State',
        'custom_function':False,
        'field_to_check':'state_of_the_meter',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'state_of_the_meter',
        'chart_type':'bar'
    },
    # {'dashboard_title':'Meter Location Inside The Premises',
        # 'custom_function':False,
    #     'field_to_check':'meter_location',
    # 'data_fomart':'single_dataset',
    #     'other_fields_to_check':[],
    #     'chart_id':'meter_class',
    #     'chart_type':'bar'
    # },
    {'dashboard_title':'Meter Brand',
        'custom_function':False,
        'field_to_check':'meter_brand',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'meter_brand',
        'chart_type':'pie'
    },
    {'dashboard_title':'Pipe Material',
        'custom_function':False,
        'field_to_check':'pipe_material',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'pipe_material',
        'chart_type':'polarArea'
    },
    {'dashboard_title':'Meter Problems',
        'custom_function':False,
        'field_to_check':'metering_problems',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'metering_problems',
        'chart_type':'horizontalBar'
    },
    {'dashboard_title':'Storage Tank Available',
        'custom_function':False,
        'field_to_check':'storage_tank_available',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'storage_tank_available',
        'chart_type':'pie'
    },
    {'dashboard_title':'Location of Storge Tank',
        'custom_function':False,
        'field_to_check':'storage_tank_location',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'storage_tank_location',
        'chart_type':'doughnut'
    },
    {'dashboard_title':'Type of Sanitation',
        'custom_function':False,
        'field_to_check':'type_of_sanitation',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'type_of_sanitation',
        'chart_type':'pie'
    },
    {'dashboard_title':'Type of Pit Latrine',
        'custom_function':False,
        'field_to_check':'choose_type_of_pit_latrine',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'choose_type_of_pit_latrine',
        'chart_type':'doughnut'
    },
    {'dashboard_title':'Type VS Category of Pit Latrine',
        'custom_function':False,
        'field_to_check':'choose_type_of_pit_latrine',
        'secondary_field':'category_type_of_pit_latrine',
        'data_fomart':'multiple_dataset',
        'other_fields_to_check':[],
        'chart_id':'type_vs_category_of_pit_latrine',
        'chart_type':'bar'
    },
    {'dashboard_title':'Category of Septic',
        'custom_function':False,
        'field_to_check':'category_of_septic',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'category_of_septic',
        'chart_type':'polarArea'
    },
    {'dashboard_title':'Type of Septic',
        'custom_function':False,
        'field_to_check':'choose_type_septic',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'choose_type_septic',
        'chart_type':'pie'
    },
    {'dashboard_title':'Type VS Category of Setptic',
        'custom_function':False,
        'field_to_check':'choose_type_septic',
        'secondary_field':'category_of_septic',
        'data_fomart':'multiple_dataset',
        'other_fields_to_check':[],
        'chart_id':'type_vs_category_of_septic',
        'chart_type':'bar'
    },
    {'dashboard_title':'Onsite Category',
        'custom_function':False,
        'field_to_check':'onsite_category',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'onsite_category',
        'chart_type':'polarArea'
    },
    {'dashboard_title':'Housing Type',
        'custom_function':False,
        'field_to_check':'type_of_housing',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'type_of_housing',
        'chart_type':'bar'
    },
    {'dashboard_title':'Premise Type',
        'custom_function':False,
        'field_to_check':'type_of_premises',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'type_of_premises',
        'chart_type':'doughnut'
    },
    {'dashboard_title':'Domestic Housing Type',
        'custom_function':False,
        'field_to_check':'type_of_residential_or_mixed_premise',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'type_of_residential_or_mixed_premise',
        'chart_type':'polarArea'
    },
    # {'dashboard_title':'Customer Satisfaction',
    #     'custom_function':True,
    #     'function_name':'test_function',
    #     # 'field_to_check':'type_of_residential_or_mixed_premise',
    #     'data_fomart':'single_dataset',
    #     # 'other_fields_to_check':[],
    #     'chart_id':'customer_satisfaction',
    #     'chart_type':'bar'
    # },
]

# *********************************************************************************************************
# portugese

# different language chart settings
pt = [
    {'dashboard_title':'Cliente conectado ao fornecedor de serviços de água',
        'field_to_check':'does_customer_have_a_connection',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'customer_connected_to_wsp',
        'chart_type':'pie'
    },
    {'dashboard_title':'Detalhes da conta conhecidos',
        'field_to_check':'customer_have_a_connection',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[{'field_name':'does_customer_have_a_connection',
           'required_value':'Sim'
        }],
        'chart_id':'account_details_known',
        'chart_type':'doughnut'
    },
    {'dashboard_title':'Cliente deseja ser conectado',
        'field_to_check':'customer_willing_to_be_connected',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[{'field_name':'does_customer_have_a_connection',
           'required_value':'Não'
        }],
        'chart_id':'customer_willing_to_be_connected',
        'chart_type':'bar'
    },
    # {'dashboard_title':'Potential Customers Connectable',
    #     'field_to_check':,
    #     'data_fomart':'single_dataset',
    #     'other_fields_to_check':[{'field_name': ,
    #        'required_value':
    #     }]
    # },
    # {'dashboard_title':'Reasons Customer is not Connected to WSP',
    #     'field_to_check':'customer_willing_to_be_connected',
    # 'data_fomart':'single_dataset',
    #     'other_fields_to_check':[{'field_name':,
    #        'required_value':
    #     }]
    # },
    {'dashboard_title':'Status da conexão',
        'custom_function':False,
        'field_to_check':'connection_status',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'connection_status',
        'chart_type':'polarArea'
    },
    {'dashboard_title':'Duração da Desconexão',
        'custom_function':False,
        'field_to_check':'disconnection_duration',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[{'field_name':'does_customer_have_a_connection',
           'required_value':'Sim'
        }],
        'chart_id':'disconnection_duration',
        'chart_type':'doughnut'
    },
    {'dashboard_title':'Fontes alternativas de água',
        'custom_function':False,
        'field_to_check':'water_sources',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'alternative_sources_of_water',
        'chart_type':'horizontalBar'
    },
    {'dashboard_title':'Status da conexão x conta conhecida',
        'custom_function':False,
        'field_to_check':'connection_status',
        'data_fomart':'multiple_dataset',
        'secondary_field':'customer_have_a_connection',
        'other_fields_to_check':[{'field_name':'does_customer_have_a_connection',
           'required_value':'Sim'
        }],
        'chart_id':'connection_status_vs_account_known',
        'chart_type':'bar'
    },
    {'dashboard_title':'Status de cobrança',
        'custom_function':False,
        'field_to_check':'billing_status',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[{'field_name':'does_customer_have_a_connection',
           'required_value':'Sim'
        }],
        'chart_id':'billing_status',
        'chart_type':'bar'
    },
    {'dashboard_title':'Status de cobrança versus status de conexão',
        'custom_function':False,
        'field_to_check':'billing_status',
        'data_fomart':'multiple_dataset',
        'secondary_field':'connection_status',
        'other_fields_to_check':[],
        'chart_id':'billing_status_vs_connection_status',
        'chart_type':'bar'
    },
    {'dashboard_title':'Frequência de entrega de faturas',
        'custom_function':False,
        'field_to_check':'frequency_of_bill_delivery',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'frequency_of_bill_delivery',
        'chart_type':'bar'
    },
    {'dashboard_title':'Frequência de entrega de faturas versus status da conta',
        'custom_function':False,
        'field_to_check':'frequency_of_bill_delivery',
        'secondary_field':'connection_status',
        'data_fomart':'multiple_dataset',
        'other_fields_to_check':[],
        'chart_id':'frequency_of_bill_delivery_vs_connection_status',
        'chart_type':'bar'
    },
    {'dashboard_title':'Com que frequência você recebe água',
        'custom_function':False,
        'field_to_check':'how_often_do_you_receive_water',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'how_often_do_you_receive_water',
        'chart_type':'polarArea'
    },
    {'dashboard_title':'Razões não faturadas',
        'custom_function':False,
        'field_to_check':'why_customer_is_not_billed',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[{'field_name':'does_customer_have_a_connection',
           'required_value':'Sim'},{'field_name':'billing_status',
           'required_value':'not_billed'}
        ],
        'chart_id':'reasons_not_billed',
        'chart_type':'pie'
    },
    {'dashboard_title':'Horas diárias de abastecimento',
        'custom_function':False,
        'field_to_check':'daily_hours',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'daily_hours',
        'chart_type':'doughnut'
    },
    {'dashboard_title':'Clientes que recebem água durante a semana',
        'custom_function':False,
        'field_to_check':'daily_hours',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'daily_hours',
        'chart_type':'pie'
    },
    {'dashboard_title':'Última vez para receber água',
        'custom_function':False,
        'field_to_check':'last_time_to_receive_water',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'last_time_to_receive_water',
        'chart_type':'bar'
    },
    {'dashboard_title':'Medidor de água conectado',
        'custom_function':False,
        'field_to_check':'water_connection',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'water_connection',
        'chart_type':'bar'
    },
    {'dashboard_title':'Status do medidor',
        'custom_function':False,
        'field_to_check':'meter_status',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'meter_status',
        'chart_type':'pie'
    },
    {'dashboard_title':'Status do medidor versus status da conexão',
        'custom_function':False,
        'field_to_check':'meter_status',
        'secondary_field':'connection_status',
        'data_fomart':'multiple_dataset',
        'other_fields_to_check':[],
        'chart_id':'meter_status_vs_connection_status',
        'chart_type':'bar'
    },
    {'dashboard_title':'Material do Medidor',
        'custom_function':False,
        'field_to_check':'meter_material',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'meter_material',
        'chart_type':'doughnut'
    },
    {'dashboard_title':'Localização do medidor',
        'custom_function':False,
        'field_to_check':'meter_location',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'meter_location',
        'chart_type':'bar'
    },
    {'dashboard_title':'Liquidação do medidor',
        'custom_function':False,
        'field_to_check':'meter_settlement',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'meter_settlement',
        'chart_type':'pie'
    },
    {'dashboard_title':'Direção do Fluxo do Medidor',
        'custom_function':False,
        'field_to_check':'meter_flow_direction',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'meter_flow_direction',
        'chart_type':'polarArea'
    },
    {'dashboard_title':'Medidor lido mensalmente',
        'custom_function':False,
        'field_to_check':'meter_read_monthly',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'meter_read_monthly',
        'chart_type':'doughnut'
    },
    {'dashboard_title':'Classe de Medidor',
        'custom_function':False,
        'field_to_check':'meter_class',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'meter_class',
        'chart_type':'bar'
    },
    {'dashboard_title':'Estado do Medidor',
        'custom_function':False,
        'field_to_check':'state_of_the_meter',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'state_of_the_meter',
        'chart_type':'bar'
    },
    {'dashboard_title':'Localização do medidor dentro das instalações',
        'custom_function':False,
        'field_to_check':'meter_location',
    'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'meter_class',
        'chart_type':'bar'
    },
    {'dashboard_title':'Marca do Medidor',
        'custom_function':False,
        'field_to_check':'meter_brand',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'meter_brand',
        'chart_type':'pie'
    },
    {'dashboard_title':'Material de Tubulação',
        'custom_function':False,
        'field_to_check':'pipe_material',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'pipe_material',
        'chart_type':'polarArea'
    },
    {'dashboard_title':'Problemas do medidor',
        'custom_function':False,
        'field_to_check':'metering_problems',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'metering_problems',
        'chart_type':'horizontalBar'
    },
    {'dashboard_title':'Tanque de armazenamento disponível',
        'custom_function':False,
        'field_to_check':'storage_tank_available',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'storage_tank_available',
        'chart_type':'pie'
    },
    {'dashboard_title':'Localização do tanque Storge',
        'custom_function':False,
        'field_to_check':'storage_tank_location',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'storage_tank_location',
        'chart_type':'doughnut'
    },
    {'dashboard_title':'Tipo de Saneamento',
        'custom_function':False,
        'field_to_check':'type_of_sanitation',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'type_of_sanitation',
        'chart_type':'pie'
    },
    {'dashboard_title':'Tipo de latrina de fossa',
        'custom_function':False,
        'field_to_check':'choose_type_of_pit_latrine',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'choose_type_of_pit_latrine',
        'chart_type':'doughnut'
    },
    {'dashboard_title':'Tipo versus categoria de latrina de fossa',
        'custom_function':False,
        'field_to_check':'choose_type_of_pit_latrine',
        'secondary_field':'category_type_of_pit_latrine',
        'data_fomart':'multiple_dataset',
        'other_fields_to_check':[],
        'chart_id':'type_vs_category_of_pit_latrine',
        'chart_type':'bar'
    },
    {'dashboard_title':'Categoria de Séptico',
        'custom_function':False,
        'field_to_check':'category_of_septic',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'category_of_septic',
        'chart_type':'polarArea'
    },
    {'dashboard_title':'Tipo de séptica',
        'custom_function':False,
        'field_to_check':'choose_type_septic',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'choose_type_septic',
        'chart_type':'pie'
    },
    {'dashboard_title':'Tipo versus categoria de setptic',
        'custom_function':False,
        'field_to_check':'choose_type_septic',
        'secondary_field':'category_of_septic',
        'data_fomart':'multiple_dataset',
        'other_fields_to_check':[],
        'chart_id':'type_vs_category_of_septic',
        'chart_type':'bar'
    },
    {'dashboard_title':'Categoria no local',
        'custom_function':False,
        'field_to_check':'onsite_category',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'onsite_category',
        'chart_type':'polarArea'
    },
    {'dashboard_title':'Tipo de Habitação',
        'custom_function':False,
        'field_to_check':'type_of_housing',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'type_of_housing',
        'chart_type':'bar'
    },
    {'dashboard_title':'Tipo de premissa',
        'custom_function':False,
        'field_to_check':'type_of_premises',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'type_of_premises',
        'chart_type':'doughnut'
    },
    {'dashboard_title':'Tipo de Habitação Doméstica',
        'custom_function':False,
        'field_to_check':'type_of_residential_or_mixed_premise',
        'data_fomart':'single_dataset',
        'other_fields_to_check':[],
        'chart_id':'type_of_residential_or_mixed_premise',
        'chart_type':'polarArea'
    },
    # {'dashboard_title':'Customer Satisfaction',
    #     'custom_function':True,
    #     'function_name':'test_function',
    #     # 'field_to_check':'type_of_residential_or_mixed_premise',
    #     'data_fomart':'single_dataset',
    #     # 'other_fields_to_check':[],
    #     'chart_id':'customer_satisfaction',
    #     'chart_type':'bar'
    # },
]

def determine_setting(language):
    '''
    Function that determines which settting to return
    based on the given language
    input:
        language - str
    output:
        list - setting of that language
    '''
    if language == "en":
        return {'status':True,'settings':en}
    elif language == "pt":
        return {'status':True,'settings':pt}
    else:
        {'status':False,
            'message':"No Chart Setting Set for Language {}".format(language)
        }